# Generated by Django 5.1.6 on 2025-02-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
